#!/bin/sh

[ -z "$1" ] && echo "Usage: $(basename $0) filename [handler]" && exit
target="$1"
shift
handle="$@"
[ -z "$handle" ] && handle=echo

for i in $(echo $PATH | tr : "\n") ; do
	[ -f "$i/$target" ] && $handle "$i/$target"
done
